/*
	Copyright (c) 2004-2006, The Dojo Foundation
	All Rights Reserved.

	Licensed under the Academic Free License version 2.1 or above OR the
	modified BSD license. For more information on Dojo licensing, see:

		http://dojotoolkit.org/community/licensing.shtml
*/

[
["AGRIGENTO","AG"],
["ALESSANDRIA","AL"],
["ANCONA","AN"],
["AOSTA","AO"],
["AREZZO","AR"],
["ASCOLI PICENO","AP"],
["ASTI","AT"],
["AVELLINO","AV"],
["BARI","BA"],
["Barletta-Andria-Trani","BT"],
["BELLUNO","BL"],
["BENEVENTO","BN"],
["BERGAMO","BG"],
["BIELLA","BI"],
["BOLOGNA","BO"],
["BOLZANO","BZ"],
["BRESCIA","BS"],
["BRINDISI","BR"],
["CAGLIARI","CA"],
["CALTANISSETTA","CL"],
["CAMPOBASSO","CB"],
["Carbonia-Iglesias","CI"],
["CASERTA","CE"],
["CATANIA","CT"],
["CATANZARO","CZ"],
["CHIETI","CH"],
["COMO","CO"],
["COSENZA","CS"],
["CREMONA","CR"],
["CROTONE","KR"],
["CUNEO","CN"],
["ENNA","EN"],
["Fermo","FM"],
["FERRARA","FE"],
["FIRENZE","FI"],
["FOGGIA","FG"],
["FORLI’-CESENA","FC"],
["FROSINONE","FR"],
["GENOVA","GE"],
["GORIZIA","GO"],
["GROSSETO","GR"],
["IMPERIA","IM"],
["ISERNIA","IS"],
["LA SPEZIA","SP"],
["L’AQUILA","AQ"],
["LATINA","LT"],
["LECCE","LE"],
["LECCO","LC"],
["LIVORNO","LI"],
["LODI","LO"],
["LUCCA","LU"],
["MACERATA","MC"],
["MANTOVA","MN"],
["MASSA-CARRARA","MS"],
["MATERA","MT"],
["MESSINA","ME"],
["MILANO","MI"],
["MODENA","MO"],
["Monza e della Brianza","MB"],
["NAPOLI","NA"],
["NOVARA","NO"],
["NUORO","NU"],
["Ogliastra","OG"],
["Olbia-Tempio","OT"],
["ORISTANO","OR"],
["PADOVA","PD"],
["PALERMO","PA"],
["PARMA","PR"],
["PAVIA","PV"],
["PERUGIA","PG"],
["PESARO E URBINO","PU"],
["PESCARA","PE"],
["PIACENZA","PC"],
["PISA","PI"],
["PISTOIA","PT"],
["PORDENONE","PN"],
["POTENZA","PZ"],
["PRATO","PO"],
["RAGUSA","RG"],
["RAVENNA","RA"],
["REGGIO DI CALABRIA","RC"],
["REGGIO NELL’EMILIA","RE"],
["RIETI","RI"],
["RIMINI","RN"],
["ROMA","RM"],
["ROVIGO","RO"],
["SALERNO","SA"],
["SASSARI","SS"],
["SAVONA","SV"],
["SIENA","SI"],
["SIRACUSA","SR"],
["SONDRIO","SO"],
["TARANTO","TA"],
["TERAMO","TE"],
["TERNI","TR"],
["TORINO","TO"],
["TRAPANI","TP"],
["TRENTO","TN"],
["TREVISO","TV"],
["TRIESTE","TS"],
["UDINE","UD"],
["VARESE","VA"],
["VENEZIA","VE"],
["VERBANO-CUSIO-OSSOLA","VB"],
["VERCELLI","VC"],
["VERONA","VR"],
["VIBO VALENTIA","VV"],
["VICENZA","VI"],
["VITERBO","VT"]
]